version: '3.4'

volumes:
  pg_project:

services:
  app:
    image: kirillkus/app
    restart: always
    ports:
      - "8081:8080"
    container_name: app
    depends_on:
      - pg_db
      - zookeeper
      - broker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
    
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - 5432:5432

  react:
    image: kirillkus/react
    ports:
      - "8082:8080"
    container_name: react
    depends_on:
      - react_bd
      - broker
      - zookeeper
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://host.docker.internal:5432/postgres
      - JAVA_OPTS="-XX:+UseG1GC -XX:MaxRAMPercentage=75"
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
    
  react_bd:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_project:/var/lib/postgresql/data
    expose:
      - "5432"
    command: -p 5432
    ports:
      - "5433:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    restart: always
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    restart: always
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1